composeexample/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

cyber_poll/urls.py
from django.contrib import admin
from django.urls import include, path
from django.shortcuts import redirect


urlpatterns = [
    path("", lambda req: redirect("/polls/")),
    path("polls/", include("polls.urls")),
    path("admin/", admin.site.urls),
]

polls/urls.py
from django.urls import path, include
from django.contrib.auth.views import LoginView, LogoutView


from . import views

app_name = "polls"
urlpatterns = [
    path("", views.IndexView.as_view(), name="index"),
    path("<int:pk>", views.DetailsView.as_view(), name="details"),
    path("<int:question_id>/vote", views.vote, name="vote"),
    path("create/", views.getCreateVote, name="vote-add"),
    path("login", LoginView.as_view(template_name="admin/login.html"), name="login"),
    path("logout", LogoutView.as_view(), name="logout"),
]

polls/models.py
from django.db import models
from django.contrib.auth.models import User


class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField("date published", auto_now_add=True)
    description_text = models.TextField(blank=True)
    imgUrl = models.CharField(max_length=1000, blank=True)

    def __str__(self):
        return self.question_text


class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text


class SecretGroup(models.Model):
    name = models.CharField(max_length=200)
    users = models.ManyToManyField(User)

    def __str__(self):
        return self.name

polls/forms.py
from django import forms

from .models import Question


class PollForm(forms.ModelForm):
    class Meta:
        model = Question
        # fields = ("question_text",)
        exclude = ("pub_date",)  # add this line

polls/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.urls import reverse
from django.views import generic
from django.db.models import F
from django.contrib.auth.decorators import login_required
from .forms import PollForm

from .models import Choice, Question


class IndexView(generic.ListView):
    template_name = "index.html"
    context_object_name = "latest_question_list"

    def get_queryset(self):
        """Return the last five published questions."""
        return Question.objects.order_by("-pub_date")


class DetailsView(generic.DetailView):
    model = Question
    template_name = "details.html"


@login_required
def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST["choice"])
    except (KeyError, Choice.DoesNotExist):
        return render(
            request,
            "details.html",
            {
                "question": question,
                "error_message": "You didn't select a choice.",
            },
        )
    else:
        selected_choice.votes = F("votes") + 1
        selected_choice.save()
        return HttpResponseRedirect(reverse("polls:details", args=(question.id,)))


class QuestionCreateView(generic.CreateView):
    model = Question
    fields = ["question_text"]

    def form_valid(self, form):
        form.instance.created_by = self.request.user
        return super().form_valid(form)


def getCreateVote(request):
    if request.method == "POST":
        form = PollForm(request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect("/polls/")

    else:
        form = PollForm()
    return render(request, "createPoll.html", {"form": form})


@login_required
def postCreateCote(request):
    questionBody = request.body
    try:
        createdQuestion = Question.objects.create(questionBody)
    except KeyError:
        return HttpResponseRedirect(reverse("polls:create"))
    else:
        createdQuestion.save()
        return HttpResponseRedirect(
            reverse("polls:details", args=(createdQuestion.id,))
        )

polls/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <title>{% block title %}Cyber Polls{% endblock %}</title>
</head>

<body>

    {% block navbar %}
        {% include  'navbar.html' %}
    {% endblock %}
    <div class="container">
        {% block content %}
        {% endblock %}

        <hr>

        <footer>
            <p>Such wow.</p>
        </footer>
    </div>
</body>
</html>

polls/templates/createPoll.html
{% extends "base.html" %}
{% block content %}

<form action="{% url 'polls:vote-add' %}" method="post">
    <!-- {% csrf_token %} -->
    {{ form }}
    <input type="submit" value="Submit">
</form>
{% endblock %}

polls/templates/details.html
{% extends "base.html" %}
{% block content %}

<legend><h1>{{ question.question_text }}</h1></legend>
<h3>{{question.description_text|safe}}</h3>
<!-- <h3>{{question.description_text}}</h3> -->
{% if question.imgUrl %}
    <img src="{{ question.imgUrl }}" width="100px" height="100"/>
{% endif %}
<ul>
    {% for choice in question.choice_set.all %}
        <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
    {% endfor %}
    </ul>
    {% if user.is_authenticated %}
        <form action="{% url 'polls:vote' question.id %}" method="post">
        <!-- {% csrf_token %} -->
            <fieldset>
                {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
                {% for choice in question.choice_set.all %}
                    <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
                    <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br>
                {% endfor %}
            </fieldset>
            <input type="submit" value="Vote">
        </form>
        <br>
    {% else %}
        <a class="login" href="{% url 'polls:login' %}">Login</a>
    {% endif %}
{% endblock %}

polls/templates/index.html
{% extends "base.html" %}
{% block content %}

<h1>Polls</h1>

{% if latest_question_list %}
    <ul>
    {% for question in latest_question_list %}
        <li><a href="/polls/{{ question.id }}">{{ question.question_text }}</a></li>
    {% endfor %}
    </ul>
    <a class="login" href="{% url 'polls:vote-add' %}">Create poll</a>
{% else %}
    <p>No polls are available.</p>
{% endif %}
{% endblock %}

polls/templates/navbar.html
<nav class="navbar">
    <a href="/polls">Polls</a>
    {% if user.is_authenticated %}
    <form action="{% url 'polls:logout' %}" method="post">
        <!-- {% csrf_token %} -->
        <button type="submit">Log Out</button>
      </form>
    {% else %}
        <a class="login" href="{% url 'polls:login' %}">Login</a>
    {% endif %}
</nav>